#!/bin/bash

if [ $# -lt 1 ]; then
  echo "USAGE: $(basename $BASH_SOURCE) <domain name> [record type]"
  exit
fi

domain=$1

if [ $# -gt 1 ]; then
  type=$2
else
  type=A
fi

function html_decode() {
  echo $@ | sed 's/&nbsp;/ /g; s/&amp;/\&/g; s/&lt;/\</g; s/&gt;/\>/g; s/&quot;/\"/g; s/#&#39;/\'"'"'/g; s/&ldquo;/\"/g; s/&rdquo;/\"/g;'
}

tempfile=$(mktemp)
cookiefile=$(mktemp)

curl -c $cookiefile -s "https://www.whatsmydns.net/#$type/$domain" > $tempfile

servers=$(cat $tempfile | grep "data-id=" | awk -F"data-id=" '{ print $2 }' | awk -F'"' '{ print $2 }')

for i in $servers
do
  info=$(cat $tempfile | grep "data-id=\"$i\"" | sed -e 's/<div //g' -e 's/class="[^\"]*"//g' -e 's/data-//g' -e 's/>//g' -e 's/^[[:space:]]*//g')
  value=$(curl -b $cookiefile -s "https://www.whatsmydns.net/api/details?server=$i&type=$type&query=$domain" | jq -r '"\(.data[].rcode) \(.data[].answers)"')
  html_decode "$(tput setaf 1)??SERVER:$(tput sgr0) $info"
  html_decode "$(tput setaf 2)>>RESULT:$(tput sgr0) $value"
done

